- arguments: [-XCPP, --cpp-define=HLINT, --cpp-ansi, --cpp-include=include]

- fixity: "infixr 8 **!, <**>"
- fixity: "infixl 7 *!, /!, ^*, *^, ^/"
- fixity: "infixl 6 +!, -!, <+>"
- fixity: "infixr 5 :!"
- fixity: "infix  4 ==!"
- fixity: "infixl 3 :-"

# this doesn't work well with Rank2Types
- ignore: {name: Eta reduce}
# Numeric.AD.Rank1.Kahn's use of CPP makes it difficult to avoid redundant parentheses
- ignore: {name: Redundant bracket, within: [Numeric.AD.Rank1.Kahn]}
- ignore: {name: Unused LANGUAGE pragma}
- ignore: {name: Reduce duplication}
